#!/bin/bash

docker build api-lb4
docker tag $(docker images --filter=dangling=true --filter "label=dev=true" -q) api-lb4:latestdev
docker rmi $(docker images --filter=dangling=true --filter "label=build=true" -q)
docker tag $(docker images --filter=dangling=true --filter "label=deploy=true" -q) api-lb4:latest

