version: '3.4'

services:
  # api-lb4:
  #   build: 
  #     context: ./api-lb4
  #     target: dev
  #   volumes:
  #     - ./api-lb4:/home/nodejs/app
  #   expose:
  #     - "3001"
  #   ports:
  #     - "3001:3001"
  api-express:
    build: 
      context: ./api-express
      target: dev
    volumes:
      - ./api-express:/home/nodejs/app

