#!/bin/bash

docker run --rm -v `pwd`/api-lb4:/home/nodejs/app -d -p 4001:3001 --name api-lb4-dev api-lb4:latestdev
docker exec -ti $(docker container ps --last 1 -q) sh -c "DEBUG=loopback:* node index.js"
